### ISSUE TITLE
Fails to handle SR on double-dropped item.

### ISSUE THREAD

**Issue by colraw** [Gogo1951/GogoLoot#103]
Seems to not be able to handle it when multiples of the same item drops and only one person (only 1 SR for that person) SR (maybe even with multiple people SR):
![image](https://user-images.githubusercontent.com/37815386/139600763-aa6835fa-a706-4daf-b009-e3762b95d86d.png)

**Comment by Gogo1951** [comment]
Hey @colraw ,

Thanks for flagging this. It's been an issue since we first launched integration with SoftRes.It.

I think the logic got a bit funky with Classic TBC though... when multiple items are present it's supposed to pause and let the loot master deal with this. 

Tagging in @AeroScripts because he's the only dev left on this project now. We've both essentially quit though. Maybe check out https://www.curseforge.com/wow/addons/gargul to see if they handle it better. Sorry mate!

**Comment by Gogo1951** [comment]
Hey @colraw ,

Hey @DieQuelle ,

After some thought, I just don't have it in me to support this project. It was fun, was happy with it, but honestly I don't have opportunities to master loot / test this like I used to. Hard for me to find groups, let alone lead groups, these days.

Check out Gargul? I think it's similar.

https://www.curseforge.com/wow/addons/gargul

Cheers!
