### ISSUE TITLE
Add support for raidroll

### ISSUE THREAD

**Issue by xCharg** [Gogo1951/GogoLoot#39]
Usecase - MC's mats, AQ's scarabs and idols, ZG's bijous and coins, every raid's random greens/blues - all of these could be (and usually are) randomly distributed in a pug.

Technically - show loot window and a button next to each item that will raidroll item and then transfer that item to person who won.

**Comment by Gogo1951** [comment]
Good call, we can add "Raid Roll" out items. Only annoying thing... if someone has full bags or isn't in the instance that makes more work for the Master Looter. Look for this in a future release.

**Comment by Gogo1951** [comment]
Closing this... not a feature I want to pursue at this time.

Was going to add an option to the Loot Destinations drop down to send items to random people... but oof. Like it creates more work and a lot more hassle. At least if you control who gets items, you know who has been told to clear their bags. If you don't... odds are way too high you're sending greens to a tank (who doesn't want more crap in their bag), or someone who has a full bag (meaning more clicking for you to go back and re-loot). 

You can give out greens to raid rolls at the end if you want, I don't see a good way to do this randomly that doesn't introduce more shit for the Master Looter to sort. 

We won't have a "button" next to items because the point is to not see that loot window at all... just click on sparkles and have them distributed. Not have to pause and click more things as you go.
