### ISSUE TITLE
Set destination for specific items

### ISSUE THREAD

**Issue by ChronosCrake** [Gogo1951/GogoLoot#62]
Hi! First off, love the addon!

So as a feature request, I think, under master looter settings, it would be great if "Ignored items" could be instead set to have a specific destination, for example, back in nax, it would have been great if we could have sent scraps to a specific player, or in kara, sending soul essence to a specific person for example. Could rename "Ignored items" to "Exception list", and have each one have a drop down next to it with the option of "Ignore" or "Alternate Destination"

**Comment by Gogo1951** [comment]
It's a lot of setup to get rolling... like you have to be in a raid with someone in order to select them as the destination. So every time you're in a raid... you'd have to toggle the destination settings. Someone asked for this in the past, and I just couldn't see setting those destinations as being less work than just trading at the end. 

I don't play much any more, ping @AeroScripts but he doesn't have a ton of free time either. Sorry mate.

**Comment by Gogo1951** [comment]
Hey @ChronosCrake ,

We won't be adding destinations for specific items... basically the logic around how to weight these vs. ignore lists is a bit more coding than we want to take on right now. 

Will be adding a few more tweaks around Auto-Greed on Greens vs. Blues sort of thing. Not quite what you were asking... but wanted to share logic on decision.

![image](https://user-images.githubusercontent.com/55365231/129391160-ea3b5f37-d859-4c50-99b2-88ad14e29350.png)
