### ISSUE TITLE
Auto random loot by class

### ISSUE THREAD

**Issue by DCSMaster** [Gogo1951/GogoLoot#85]
Is it possible to have an option for automatic rolls to do a random <number of people in raid> and assign loot to them.  For instance, All green loot have it go to a random player in the run.  Or Round Robin type where it will just go in sequence

**Comment by Gogo1951** [comment]
Hey @DCSMaster ,

This has been brought up before, same answer. (=

Unfortunately I'm not interested in the edge cases where someone has a full bag... or giving items to tanks who don't want items in their bags. Admittedly, it's less of an issue in TBC since we all seem to have bigger bags, but gonna stick with original answer and say that if you want to random out gear just roll it off at the end. Sorry!

Coding these ends up taking a lot more time than I thought / hoped. Really not interested in adding any other features in TBC. Will fix bugs, but past that... likely not going to make any more changes for a while.

PRs welcome!

Cheers!
